### ISSUE TITLE
Partial translation of printer settings dialog box

### ISSUE THREAD

**Issue by alainroger** [zdohnal/system-config-printer#80] opened 2017-12-01 13:48 UTC
My mom uses french localization of Ubuntu 17.10 with KDE.
In the printer dialog box, part of text is in english and other part in french.

i discovered that issue comes from PPD file that is not adequate regarding to localization (French) and only english version is used as you can see on:

<a href="http://fr.tinypic.com?ref=2m67o1u" target="_blank"><img src="http://i66.tinypic.com/2m67o1u.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

you have attached the original file which is located in: /etc/cups/ppd, in my mom's case it's called : EPSON_XP-332_335_Series.ppd

now i can modify it and change few strings into french localization and here is the result:

<a href="http://fr.tinypic.com?ref=20rpjs" target="_blank"><img src="http://i68.tinypic.com/20rpjs.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

Nobody should modify manualy this file in order to have it localized. Something is wrong as i install french driver from EPSON directly on my mom's laptop.

Several other people told me that they have the same issue with Spanish or other localization.

**Comment by zdohnal** [comment] 2017-12-01 14:21
Hi,
your issue is duplicate of #79

**Closed by zdohnal** 2017-12-01 14:21 UTC

**Comment by zdohnal** [comment] 2017-12-04 09:43
Hi,
your issue is duplicate of #79
