### ISSUE TITLE
What do I need multiple instances of it for?

### ISSUE THREAD

**Issue by saitam1** [zdohnal/system-config-printer#116] opened 2018-08-23 09:35 UTC
When clicking the symbol above multiple times it opens multiple instances. What for?

![print](https://user-images.githubusercontent.com/23245678/44517655-8fbd0680-a6c8-11e8-83fb-f1d2033cff78.png)

**Comment by zdohnal** [comment] 2018-08-30 10:12
Hi,
it is duplicate of #103 . Closing.

**Closed by zdohnal** 2018-08-30 10:12 UTC
