### ISSUE TITLE
'orientation-requested' and 'print-quality' has value '0' error messages

### ISSUE THREAD

**Issue by Atalanttore** [zdohnal/system-config-printer#105] opened 2018-04-23 19:52 UTC
Hi,

CUPS stopped working suddenly on my Ubuntu machine. So I opened the settings of my printer in the _system-config-printer_ 1.5.9 utility which welcomes me with two error messages.

First dialog:
`Option 'orientation-requested' has value '0' and cannot be edited.`

Second dialog:
`Option 'print-quality' has value '0' and cannot be edited.`

After clicking OK two times _Apport_ reported an error in
`/usr/share/system-config-printer/system-config-printer.py`

because of
`system-config-printer.py crashed with TypeError in __init__(): debugprint() takes 1 positional argument but 2 were given`

CupsErrorLog:
```
[cups-deviced] PID 19691 (gutenprint52+usb) stopped with status 1!
Unable to create "/etc/cups/subscriptions.conf.N": No such file or directory
```

See also: [Bug report](https://bugs.launchpad.net/ubuntu/+source/system-config-printer/+bug/1766107) at Launchpad.

Regards,
Atalanttore

**Comment by zdohnal** [comment] 2018-06-26 07:36
Hi,
thank you for reporting this issue! Unfortunately, most of the issue is problems in other printing components - CUPS, gutenprint - so it is difficult to tell if the problem really lies in s-c-p. Only issue, which I can totally tell it is s-c-p is crash due TypeError. But there is again difficult to tell where problem was without a backtrace or traceback - apport files weren't so much helpful in this regard.
Would you mind giving me any traceback of TypeError crash? And CUPS and gutenprint issue please report on Ubuntu support to correct components.

**Comment by jnumm** [comment] 2018-08-23 09:40
Hi,

I haven't experienced the crash but I tried to look for debugprint usage errors, and found one (where instead of `,` there should be `%`). My method was to use `git grep 'debugprint.*%'` and its variations and look through the results.

https://github.com/zdohnal/system-config-printer/blob/8b359b28d4af1fdb976779c83f1afc80270f978b/newprinter.py#L1052

**Comment by zdohnal** [comment] 2018-08-30 10:06
@jnumm Nice find, Juhani! Thank you! I'll close this issue with commit 027ed86 , because it is only clear problem with s-c-p from the issue.

**Closed by zdohnal** 2018-08-30 10:06 UTC
