### ISSUE TITLE
Bubble help config option

### ISSUE THREAD

**Issue by mvogt1** [zdohnal/system-config-printer#92] opened 2018-02-08 10:52 UTC
I'm using the system-config-printer in version 1.4.8 and I cannot build 1.5.11 on RHEL to test if this feature is already implemented:

When I have the applet open, in the status bar, I see the printjobs from my printer, but unfortunately this is a departement printer an I see all printjobs, which gets more and more disturbing over weeks.

Is it possible to make the bubble help configurable?

**Comment by zdohnal** [comment] 2018-02-08 12:32
Hi,

system-config-printer-applet is not running in the newest version for Gnome, KDE and Cinnamon desktops (https://github.com/zdohnal/system-config-printer/pull/41), because their settings-daemon claims D-Bus interfaces provided by system-config-printer applet.
So if you have Gnome, KDE or Cinnamon desktop, the "bubble" is managed by its settings-daemon. I'm sorry, I will not add features for applet, which probably will be removed for all desktops.
Actually I am not sure why you are seeing messages for all printjobs - don't you have your CUPS queue shared or are you connected to a print server, not to your local CUPS? But this is configuration issue, not a bug.
Because of both reasons mentioned above, I'm closing this issue.

**Closed by zdohnal** 2018-02-08 12:32 UTC
